[package]
name = "bronze-magpie"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.103"
axum = "0.8.9"
instant-acme = { path = "/Users/jmayclin/workspace/instant-acme"}
rcgen = { path = "/Users/jmayclin/workspace/rcgen/rcgen"}
rustls = { version = "0.23", default-features = false, features = ["logging"] }
rustls-pemfile = "2.2.0"
rustls-rustcrypto = "0.0.2-alpha"
rustls-webpki = "0.103.13"
time = "0.3.53"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
tokio-rustls = { version = "0.26", default-features = false}
tower = "0.5.3"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"]}
website = {path = "../website"}
x509-parser = "0.18.1"
